### ISSUE TITLE
Link to Project

### ISSUE THREAD

**Issue by Devdre1909** [Oluwasetemi/oluwasetemi.dev#11]
Hi Setemi, seems like you made a mistake in the link you provided for the project, you wrote https://www.oluwasetemidev, missing the dot.

**Comment by Oluwasetemi** [comment]
thanks, @Devdre1909. Just noticing the comments now.

**Comment by Oluwasetemi** [comment]
I will fix it this weekend.

**Comment by Oluwasetemi** [comment]
@Devdre1909 can you point me to the exact place I wrote the above? Good to hear from you. How is your career going? We should catchup on whatsApp? Mine is going fine as well. Doing more cloud and AWS related as a Full Stack Engineer. Got an opportunity to teach at AltSchool Africa part time. Moved out the country to Jamaica as well. Life has been fair with good tidings. I hope the same for you as well. Buzz me on whatsApp if you want to catch up. Have a great week ahead.
