### ISSUE TITLE
Fix the URL generated for the RSS feed, the link is not pointing to the right resources.

### ISSUE THREAD

**Issue by Oluwasetemi** [Oluwasetemi/oluwasetemi.dev#16]
// TODO:
Implement a fix for the URL transformation issue in oluwasetemi.dev such that getBlogFeed function return `https://oluwasetemi.dev/blog/` instead of `https://oluwasetemi.dev/`

Replace line 287 with `${siteUrl}/blog/${stripSlash(edge.node.fields.slug)}`.

Such that the rss feeds generated [here](https://www.oluwasetemi.dev/rss.xml) will have link to be `https://oluwasetemi.dev/blog/2021-in-review/` and not `https://oluwasetemi.dev/2021-in-review/`

**Comment by Rolalove** [comment]
I'm unable to clone the repo, keep getting an error.
git clone https://github.com/Oluwasetemi/oluwasetemi.dev.git
Cloning into 'oluwasetemi.dev'...
remote: Enumerating objects: 2063, done.
remote: Counting objects: 100% (313/313), done.
remote: Compressing objects: 100% (144/144), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 7957 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by Oluwasetemi** [comment]
Good lord, see who is here, it might be the network. You can even create the changes online as well. Just changing a line in the gatsbyconfig file @Rolalove

**Comment by Rolalove** [comment]
Done, Thank you for the help sir.
Open source wayyy...

**Comment by Oluwasetemi** [comment]
Great Yay!!, I cannot see the PR over at my end. Ensure you created the PR to my end.
